# Generated by Django 5.0.4 on 2024-05-15 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havayolları', '0003_alter_yolcular_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='havaalanlari',
            name='kod',
            field=models.CharField(default='JCK', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ucuslar',
            name='kalkis_havaalani_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Kalkış', to='havayolları.havaalanlari'),
        ),
        migrations.AlterField(
            model_name='ucuslar',
            name='varis_havaalani_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Varış', to='havayolları.havaalanlari'),
        ),
    ]
