# Generated by Django 5.0.4 on 2024-04-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ucuslar',
            fields=[
                ('ucus_id', models.AutoField(primary_key=True, serialize=False)),
                ('kalkis_havaalani_id', models.CharField(max_length=50)),
                ('varis_havaalani_id', models.CharField(max_length=50)),
                ('kalkis_tarihi', models.DateField()),
                ('varis_tarihi', models.DateField()),
                ('havayolu_adi', models.CharField(max_length=255)),
                ('ucus_sure', models.IntegerField()),
                ('ucak_no', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ucuslar',
            },
        ),
    ]
