# Generated by Django 5.0.4 on 2024-04-30 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucuslar', '0002_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Havaalanlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('havaalani_ismi', models.CharField(max_length=100)),
                ('sehir', models.CharField(max_length=100)),
                ('ulke', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'havaalanlari',
            },
        ),
        migrations.CreateModel(
            name='Yolcular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
                ('soyisim', models.CharField(max_length=50)),
                ('pasaport_no', models.CharField(max_length=20, unique=True)),
                ('dogum_tarihi', models.DateField()),
            ],
            options={
                'db_table': 'yolcular',
            },
        ),
        migrations.CreateModel(
            name='YolcuUcuslari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucuslar.ucuslar')),
                ('yolcu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucuslar.yolcular')),
            ],
            options={
                'db_table': 'yolcu_ucuslari',
            },
        ),
    ]
