# Generated by Django 5.0.4 on 2024-05-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ucuslar', '0005_airport_contry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='contry',
            new_name='country',
        ),
    ]
