# Generated by Django 5.0.4 on 2024-05-01 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ucuslar', '0007_passenger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passenger',
            new_name='Passengers',
        ),
    ]
