# Generated by Django 5.0.4 on 2024-05-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('havayolları', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yolcular',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
