# Generated by Django 5.0.4 on 2024-04-30 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('havayolları', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Havaalanlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('havaalani_ismi', models.CharField(max_length=100)),
                ('sehir', models.CharField(max_length=100)),
                ('ulke', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'havaalanlari',
            },
        ),
        migrations.CreateModel(
            name='Ucuslar',
            fields=[
                ('ucus_id', models.AutoField(primary_key=True, serialize=False)),
                ('kalkis_havaalani_id', models.CharField(max_length=50)),
                ('varis_havaalani_id', models.CharField(max_length=50)),
                ('kalkis_tarihi', models.DateField()),
                ('varis_tarihi', models.DateField()),
                ('havayolu_adi', models.CharField(max_length=255)),
                ('ucus_sure', models.IntegerField()),
                ('ucak_no', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ucuslar',
            },
        ),
        migrations.CreateModel(
            name='Yolcular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID',null=True)),
                ('isim', models.CharField(max_length=50)),
                ('soyisim', models.CharField(max_length=50)),
                ('pasaport_no', models.CharField(max_length=20, unique=True)),
                ('dogum_tarihi', models.DateField()),
            ],
            options={
                'db_table': 'yolcular',
            },
        ),
        migrations.CreateModel(
            name='YolcuUcuslari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yolcular', to='havayolları.ucuslar')),
                ('yolcu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucuslar', to='havayolları.yolcular')),
            ],
            options={
                'db_table': 'yolcu_ucuslari',
            },
        ),
    ]
